CREATE TABLE IF NOT EXISTS bearbase (
    `Character` VARCHAR(36) CHARACTER SET utf8,
    `Origin` VARCHAR(53) CHARACTER SET utf8,
    `Creator` VARCHAR(52) CHARACTER SET utf8,
    `Notes` VARCHAR(657) CHARACTER SET utf8
);
INSERT INTO bearbase VALUES
    ('"Master" Po Ping','Kung Fu Panda',NULL,'An energetic and overweight giant panda who becomes the Dragon Warrior.'),
    ('Akakabuto','Ginga Nagareboshi Gin',NULL,'A power-hungry bear from the fictional Japanese Mountains of Ohu. His name means "red-helmet", after the unusual red patch of fur lining his backbone. Bloodthirsty and full of wrath, he terrorizes the people in nearby villages and forms alliances with other powerful bears to build his own fortress in the mountains. He is the main villain in Ginga Nagareboshi Gin, and has a brief cameo in Ginga Legend WEED via narrated flashback.'),
    ('Aloysius','Brideshead Revisited','Evelyn Waugh','Sebastian Flyte''s teddy bear.'),
    ('Ambrose','Rupert the Chick','Arthur White','Best friend of Rupert the Chick.[2]'),
    ('Amy','Bananas In Pyjamas',NULL,'One of three teddies of Cuddles Avenue.'),
    ('Andy Panda','Walter Lantz',NULL,'He has a girlfriend called Miranda Panda, and a father called Andrew Senior. They have appeared in many cartoons and comic books. One of his comic book adventures was drawn by Carl Barks. John Stanley also did Andy Panda comic book work.[1]'),
    ('Anne Marie Doddel','Tom Poes','Marten Toonder','Love interest and later wife of Olivier B. Bommel.[3]'),
    ('Archie','Dr. Dolittle 2',NULL,'A wise-cracking circus-performing bear.'),
    ('Baby Bear','Sesame Street',NULL,'Son of Papa and Mama Bear and eventually brother of his new baby sister Curly and a good friend of Telly Monster.'),
    ('Baloo','The Jungle Book (Disney)',NULL,'Pilot of the transport plane "Sea Duck" from TaleSpin. (Character adaption of Baloo from 1967 animated film.) He is also a friend of Mowgli and Bagheera in The Jungle Book. Voiced by Phil Harris in the first film, John Goodman in the second film and Bill Murray in the CGI remake.'),
    ('Baloo','The Jungle Book, The Second Jungle Book','Rudyard Kipling','A sloth bear who is Mowgli''s mentor and friend.'),
    ('Bamboo Pandamonium[Note 1]','Mega Man X8','Capcom','Robotic panda encountered as a boss in a bamboo forest. Works with the main villain, Sigma, to bring about his vision of the world.[24]'),
    ('Bamse','Bamse','Rune Andréasson','The strongest bear in the whole world.'),
    ('Banjo','Banjo-Kazooie','Rare','Laid back and easygoing. Titular hero alongside the loudmouthed bird Kazooie.[25]'),
    ('Barnacles','The Octonauts',NULL,'The Captain of the Octonauts ship.'),
    ('Barney Bear','Barney Bear',NULL,'A grumpy brown bear, who finds it hard to cope with the annoyances around him.'),
    ('Barnstable Bear','Pogo','Walt Kelly','A simple-minded bear.'),
    ('Barry Bear','Angry Beavers',NULL,NULL),
    ('Basil the Bear','Sesame Park',NULL,NULL),
    ('Bear','WordWorld',NULL,'A bear that is made up of the words B, E, A and R.'),
    ('Bear','Bear in the Big Blue House',NULL,'Bear is a bear that lives in a big blue house with his friends Tutter the mouse, Pip and Pop the otters, Ojo the bear cub, Treelo the lemur, and Shadow the shadow.'),
    ('Bear','Bedknobs and Broomsticks',NULL,'The Bear is a sailor and fisherman on the Isle of Naboombu who pulls the bed, with Miss Price''s group on it, out of the lagoon with his fishing pole, and takes them to see the King after warning them of his temper.'),
    ('Bear','Bear (comic)','Jamie Smart',NULL),
    ('Bear','Franklin','Paulette Bourgeois','A brown bear who is Franklin''s best friend.'),
    ('Bear','The Honey and Bear Stories','Ursula Dubosarsky','Bear lives with the little bird Honey, a silvereye, native to Australia.'),
    ('Bear','Bear','Marian Engel','The titular unnamed bear whose relationship with a librarian is the subject of the novel.'),
    ('Bear Family','Berenstain Bears','Stan and Jan Berenstain','The Family consists of Father Bear, Mother Bear, Brother Bear, Sister Bear and eventually Honey Bear.'),
    ('Beary Barrington','The Country Bears',NULL,NULL),
    ('Ben','The Life and Times of Grizzly Adams',NULL,'Played by a live bear named Bozo'),
    ('Ben','The Life and Times of Grizzly Adams','Charles Sellier',NULL),
    ('Bernard','Bernard',NULL,'also known as Backkom'),
    ('Bert','Willa''s Wild Life',NULL,NULL),
    ('Bi-Polar Bear','Queer Duck',NULL,'One of Queer Duck''s friends. He often makes bad jokes that he alone finds funny.'),
    ('Biffo the Bear','The Beano','Dudley D. Watkins',NULL),
    ('Big Double','Little Tricker the Squirrel Meets Big Double the Bear','Ken Kesey
Barry Moser','An obese grizzly bear, who is the main antagonist. He terrorizes the animals of Topple''s Bottom just by eating them all up in one single solitary operation, until he gets outmatched by Little Tricker the Squirrel.[23]'),
    ('Big Mikey','Bunsen Is a Beast',NULL,'A Black Bear that was given to and named after Mikey in the episode, Bearly Acceptable Behavior.'),
    ('Birre Beer','Birre Beer','Phiny Dick, Ton Beek, Andries Brandt, Eiso Toonder','A naïve little bear who lives in a forest with his friends Socratov the mouse and Mirre, the daughter of a woodsman.[4]'),
    ('Blossom','Whisker Haven Tales with the Palace Pets',NULL,'Mulan''s panda cub and member of the Palace Pets.'),
    ('Blubber Bear','Wacky Races',NULL,'Luke''s racing partner.'),
    ('Bluebear','The 13 1/2 Lives of Captain Bluebear','Walter Moers','A Chromabear living in Zamonia who has many adventures. He is intelligent and amiable.'),
    ('Bobby Bear','Bobby Bear','Kitsie Bridges, Dora McLaren, Wilfred Haughton, Meg',NULL),
    ('Bobo','The Simpsons',NULL,'Mr Burns'' treasured childhood teddy bear.'),
    ('Bobo','Bobo','Lars Mortimer',NULL),
    ('Bobo the Bear','Muppets Tonight',NULL,'He is easily amused yet often dry, sarcastic, and slightly befuddled.'),
    ('Bojan','Bojan the Bear',NULL,'A painter who paints his own world with three colours.'),
    ('Bongo','Fun and Fancy Free',NULL,'A circus bear.'),
    ('Boo Boo','The Yogi Bear Show',NULL,'Boo-Boo Bear resides in Jellystone Park and would often question Yogi Bear about why they are trying to steal picnic baskets while evading Ranger Smith.'),
    ('Boog','Open Season',NULL,'Elliot''s best friend and the protagonist of the film and its sequels. Voiced by Martin Lawrence and Mike Epps'),
    ('Boris','64 Zoo Lane',NULL,NULL),
    ('Br''er Bear','Song of the South',NULL,'Dimwitted bear who works together with Br''er Fox.'),
    ('Br''er Bear','"Uncle Remus" stories','Joel Chandler Harris','A slow witted bear working with Br''er Fox to capture and eat Br''er Rabbit.'),
    ('Breezly','Breezly and Sneezly',NULL,'A comical, resourceful, polar bear, who sticks with his friend Sneezly.'),
    ('Brommy & Tommy','Brommy & Tommy','Jan Dirk van Exter','Two cute little bears who are good friends.[5]'),
    ('Brother Bear','Coonskin',NULL,'A satirical subversion of Joel Chandler Harris and Disney''s similar character from Song of the South, reimagined as an African-American.[22]'),
    ('Brummel','Brummel und Knickebein','Rolf Kauka','A bear whose sidekick is Knickebein the raven.[8]'),
    ('Bungle','Rainbow',NULL,'An inquisitive bear but also clumsy and complains a lot about the other characters.'),
    ('Burble','Danger Rangers',NULL,'A polar bear cartoon.'),
    ('Bussi Bär','Bussi Bär','Rolf Kauka','A little bear whose comic strip ran from 1973 until 2013.[8]'),
    ('Buttons the Bear','Puppets Who Kill',NULL,NULL),
    ('Chen Stormstout','Warcraft III: The Frozen Throne','Blizzard Entertainment','Warrior and Brewmaster of the Pandaren people.[26] Playable character in the Heroes of the Storm.[27]'),
    ('Choko','Animal Boxing','Gammick Entertainment','Male brown bear boxer.'),
    ('Cindy Bear','The Yogi Bear Show',NULL,'Yogi Bear''s girlfriend. First appears as a blue bear in yellow garments, but is redesigned in Hey There, It''s Yogi Bear!.'),
    ('Colargol','Les Aventures de Colargol',NULL,'The series was produced from 1967 to 1974, comprising 53 thirteen-minute episodes which were broadcast in many European countries. Les Aventures de Colargol was renamed Barnaby when it was dubbed into English and broadcast in the UK by the BBC. The series underwent another name change when a second dubbed version of the series was shown in Canada (and also in the UK and Ireland), this time as Jeremy the Bear.'),
    ('Corduroy','Corduroy','Don Freeman','A teddy bear who hopes to be owned by a girl named Lisa.'),
    ('Cornelius Bear','Achewood','Chris Onstad',NULL),
    ('Corporal','Penguins of Madagascar',NULL,'A polar bear who is the member of the North Wind.'),
    ('Cub','Happy Tree Friends',NULL,'Causes trouble, usually through dangerous activities while his father does not pay attention.'),
    ('Disco Bear','Happy Tree Friends',NULL,'A light orange-colored bear with an orange afro and sideburns who likes to dance to disco music. He wears 1970s style clothing, including a yellow leisure jacket, yellow bell-bottom pants, and orange and white dancing platform shoes.'),
    ('Eddy and the Bear','Collingwood & Co.',NULL,NULL),
    ('Flippy','Happy Tree Friends',NULL,'Flippy is a green male bear. He wears dog tags around his neck, a military uniform and a green beret with checkered crest on his head. He is a retired veteran soldier in the Army. He fought in the Weaponized Animal Regiment (The W.A.R), and has an obsession with making booby traps inspired by the Viet Cong, as well as a flashback of his experience of being held captive by them (as seen in Easy For You to Sleigh). But he sometimes "flips out" everytime he sees or hears something related to war and kills anyone in sight; hence the name.'),
    ('Fluffy','Duckman',NULL,'One of Duckman''s two Care Bear-esque teddy-bear office assistants. Fluffy is pink. Fluffy and his co worker Uranus try to get Duckman to act kindly and more politically correct.'),
    ('Fozzie Bear','The Muppets',NULL,'An orange-brown, fozzie bear who often wears a brown pork pie hat and a pink-and-white polka-dot necktie. Serves as the show''s stand-up comic.'),
    ('Freddy Fazbear','Five Nights at Freddy''s','Scott Cawthon','He is an animatronic bear that was built for Freddy Fazbear''s Pizza. He has five counterparts: Golden Freddy/Fredbear, Toy Freddy, Withered/Old Freddy, Purple/Shadow Freddy, Phantom Freddy, and Nightmare. the most of any animatronic in the series. Golden Freddy appears in Five Nights at Freddy''s and Five Nights at Freddy''s 2. Toy Freddy appears only in Five Nights at Freddy''s 2 along with Withered/Old Freddy and Purple/Shadow Freddy. Phantom Freddy only appears in Five Nights at Freddy''s 3. Golden Freddy appears as "Fredbear" in Five Nights at Freddy''s 4. Nightmare only appears in Five Nights at Freddy''s 4. Nightmare is the same model as "Fredbear".'),
    ('Fuzz','Fuzz & Pluck','Ted Stearn','A naïve, gullible teddy bear with self-doubt.[9]'),
    ('Genma Saotome','Ranma ½','Rumiko Takahashi',NULL),
    ('Gentle Ben','Gentle Ben',NULL,'About a boy and his tame bear.'),
    ('Gentle Ben','Gentle Ben','Walt Morey','A grizzly bear in the book, though the TV series and movies make him a black bear.'),
    ('George and Junior','Metro-Goldwyn-Mayer cartoons',NULL,'Two bears inspired by George and Lennie from John Steinbeck''s Of Mice and Men.'),
    ('Ginko Yurishiro','Yuri Kuma Arashi',NULL,NULL),
    ('Giorgione','Pinky','Massimo Mattioli','Best friend of Pinky the rabbit.[10]'),
    ('Gohin','Beastars','Paru Itagaki','One of the main characters. A giant panda who acts as a doctor and therapist for carnivores in the Black Market'),
    ('Gordon','Camp Lazlo',NULL,'A bear bean scout.'),
    ('Grizzly','Shirokuma Cafe',NULL,NULL),
    ('Grizzly Bear','Happy Tree Friends',NULL,'A male grizzly bear in the episode "Take a Hike".'),
    ('Grizzly Bear','We Bare Bears',NULL,'One of the three brothers trying to fit in with human society.'),
    ('Grizzly Slash[Note 2]','Mega Man X5','Capcom','Robotic grizzly bear encountered as a boss on a large truck after he becomes berserk from the "Sigma Virus".[28]'),
    ('Grizzy','Grizzy and the Lemmings',NULL,'A bear who constantly battles a clan of lemmings, with results that always end with both Grizzy and the lemmings losing in some bizarre, comical way.'),
    ('Harvey','A Father''s Day Thank You','Janet Nolan','A bear cub who gives a thankyou card to his dad.'),
    ('Hei Bai','Avatar: The Last Airbender',NULL,'Spirit of the forests that takes the animal form of a panda bear.'),
    ('Herbert Percival Bear, Esquire','Club Penguin','Disney Interactive Studios','The main antagonist of Club Penguin.'),
    ('Humphrey B. Bear','Nine Network',NULL,'A tall, shaggy honey-loving brown bear with a large, glossy nose, straw boater hat, tartan waist-coat and oversized yellow bow-tie.'),
    ('Humphrey B. Bear','Humphrey B. Bear',NULL,'A tall, shaggy brown bear with a large, glossy nose, straw boater, tartan waist-coat and oversized yellow bow-tie.'),
    ('Humphrey the Bear','Walt Disney shorts',NULL,'A bear who usually harasses Donald Duck and park ranger J. Audubon Woodlore.'),
    ('Ice Bear','We Bare Bears',NULL,'One of the three brothers trying to fit in with human society.'),
    ('Io','Marvel Comics','Greg Pak, Gang Hyuk Lim','A "half-moon" bear spirit sealed inside a magic mask. Companion to Crescent. From Earth-616'),
    ('Iorek Byrnison','His Dark Materials','Philip Pullman','A male armored polar bear. An honorable friend to Lyra and the rightful king of Svalbard.'),
    ('Issi Noho','Issi Noho','Keith Chatfield',NULL),
    ('Ivan the Bear','Brutal: Paws of Fury','GameTek','Russian brown bear who fights using Soviet military style.[29]'),
    ('Jack Bear','Goldie & Bear',NULL,'Mama & Papa Bear''s son who met Goldie, after she accidentally broke his favourite chair'),
    ('Jake The Polar Bear','Jim Henson''s Animal Show',NULL,'One of 2 hosts of Jim Henson''s Animal Show'),
    ('Jasper the Bear','Jasper the Bear','James Simpkins','Debuted in a gag comic and later became mascot of Jasper National Park [11]'),
    ('Jelly','Xuxa',NULL,NULL),
    ('Katahdin','Prophecy 1979',NULL,'Mutated Killer Bear'),
    ('Kenai','Brother Bear',NULL,'An Alaskan Inupiat Inuit teenager who is transformed into a grizzly bear by Sitka''s spirit in the Aurora after killing Koda''s mother. Voiced by Joaquin Phoenix in the first film and Patrick Dempsey in the second film. Despite Kenai for his Native American appearance as an Eskimo his name means"Flat land"" in Athabascan language and is also named after Alaska''s Kenai Peninsula Borough.'),
    ('Kevin','Zootopia',NULL,'Mr. Big''s most trusted henchman, and a member of the Tundratown mafia'),
    ('Kissyfur','Kissyfur',NULL,'A little boy bear that lives with his father in the swamps.'),
    ('Kit Cloudkicker','TaleSpin',NULL,'Formerly an air pirate, then after escaping became a navigator for Baloo.'),
    ('Koda','Brother Bear',NULL,'An orphaned Alaskan grizzly bear cub, who becomes a great friend to Kenai. Voiced by Jeremy Suarez. Koda means"Friend" in Sioux language.'),
    ('Kozlov Leifonovich Grebnev','Biomega','Tsutomu Nihei',NULL),
    ('Kuma','Tekken','Namco','Bodyguard and pet of Heihachi Mishima.'),
    ('Kumajiro','Hetalia: Axis Powers',NULL,'A pet polar bear owned by the personification of Canada. He is often shown to not recognize Canada as a joke that no one knows Canada, even his pet.'),
    ('Kumazo','Animal Boxing','Gammick Entertainment','Male polar bear boxer.'),
    ('Lala Hiyama','Knights of Sidonia',NULL,'A talking bear who serves as "dorm mother."'),
    ('Lars','The Little Polar Bear','Hans de Beer','Adapted into a TV Series for BBC in 1990s and four films by Warner Bros.'),
    ('Li Li Stormstout','World of Warcraft: Mists of Pandaria','Blizzard Entertainment','Niece and traveling companion of Chen Stormstout.[30] Playable character in the Heroes of the Storm.[31]'),
    ('Life Beauty','Yuri Kuma Arashi',NULL,NULL),
    ('Life Cool','Yuri Kuma Arashi',NULL,NULL),
    ('Life Sexy','Yuri Kuma Arashi',NULL,NULL),
    ('Little Bear','Little Bear','Else Holmelund Minarik','Illustrated by Maurice Sendak and adapted into a TV Series by Nelvana.'),
    ('Little John','Walt Disney''s Robin Hood',NULL,'John Little (Robin Hood changed his name into Little John) is a legendary fellow outlaw of Robin Hood.'),
    ('Lola','Lola Panda','BeiZ Ltd.','An anthropomorphic panda who typically wears a pink short-sleeved shirt, knee length jeans, and sneakers.'),
    ('Lord Noriyuki','Usagi Yojimbo','Stan Sakai',NULL),
    ('Lots-o''-Huggin'' Bear','Toy Story 3',NULL,'Stuffed bear that is the main antagonist in Toy Story 3.'),
    ('Luk','Balto',NULL,NULL),
    ('Lulu','Bananas In Pyjamas',NULL,'One of three teddies of Cuddles Avenue.'),
    ('Lulu Yurigasaki','Yuri Kuma Arashi',NULL,NULL),
    ('Lumpjaw','Fun and Fancy Free',NULL,'Main antagonist to Bongo.'),
    ('Malloy','Brickleberry',NULL,'A very crude, racist, sexist grizzly bear cub that play video games.'),
    ('Marezou','Girl Friend BETA',NULL,NULL),
    ('Mary Plain','Mary Plain','Gwynedd Rae',NULL),
    ('Master Yo','Yin Yang Yo!',NULL,'Father and teacher of Yin and Yang.'),
    ('Maxie','Chilly Willy',NULL,'Maxie the polar bear is one of Chilly Willy''s best friends. He is a white polar bear first seen in Polar Fright when he musted takes care of a dog to not wake up. Maxie meeted Chilly Willy in Chilly Chums when he saved Maxie by a hunter.'),
    ('Misha','Masha and the Bear',NULL,'A retired circus bear acts as a fatherly figure to a young girl named Masha.'),
    ('Misha','The Foundation Pit','Andrei Platonov',NULL),
    ('Misha','Warcraft III: The Frozen Throne','Blizzard Entertainment','Brown bear companion of the beastmaster Rexxar.[32] Misha appears in the Heroes of the Storm as well, as a part of Rexxar''s ability kit.[33]'),
    ('Mister Bultitude','That Hideous Strength','C. S. Lewis','The Great Bear of Logres, resident at St. Anne''s.'),
    ('Molly Cunningham','TaleSpin',NULL,'She is Rebecca Cunningham''s yellow-furred, 6-year-old daughter.'),
    ('Moneybags','Spyro 2: Ripto''s Rage!','Insomniac Games','A greedy bear who has an obsession and love for money.'),
    ('Monokuma','Danganronpa','Spike','A robotic black & white teddy bear that takes over Hope''s Peak Academy and finds joy in spreading despair.'),
    ('Mor''du','Brave, The Legend of Mor''du',NULL,'A violent, massive bear with the strength of ten men. Formerly a human Scottish prince, who was transformed by a spell he acquired in an attempt to defeat his brothers for total control of an ancient kingdom.'),
    ('Mord','Borne','Jeff Vandermeer',NULL),
    ('Morgan','Bananas In Pyjamas',NULL,'One of three teddies of Cuddles Avenue.'),
    ('Mouk','Mouk',NULL,'A globe-trotting bear.'),
    ('Mrs. Bruin','Tiger Tim (aka The Bruin Boys)','Julius Stafford Baker,[6] Herbert Sydney Foxwell [7]','A female bear who works as a teacher. The character was originally a hippopotamus named Mrs. Hippo.[6]'),
    ('Muk','Balto',NULL,NULL),
    ('Nassur','Tomorrow''s Pioneers',NULL,'An aggressively anti-Semitic teddy bear'),
    ('Natsu','Kuma Miko: Girl Meets Bear',NULL,NULL),
    ('Naughty Bear','Naughty Bear','Artificial Mind and Movement','A revenge-driven bear and protagonist of the eponymous game.'),
    ('Nestor','Moky et Poupy','Roger Bussemy','Pet bear of two Native American children, Moky and Poupy.[12]'),
    ('Nev the Bear','Bear Behaving Badly',NULL,'A small, blue puppet bear.'),
    ('Ojo','Bear in the Big Blue House',NULL,'A small bear who is one of Bear''s friends and helps Bear do all kinds of stuff.'),
    ('Old Bear','Old Bear and Friends','Jane Hissey','An elderly dusty teddy bear, whom the other toys look up as a fearless, yet wise leader.'),
    ('Old Ben','The Bear','William Faulkner',NULL),
    ('Old Majesty','Irish Red','Jim Kjelgaard','A large bear that terrorizes the wilderness.'),
    ('Olivier B. Bommel (Oliver B. Bumble)','Tom Poes','Marten Toonder','A bear who lives like a nobleman. Best friend of Tom Poes.[3]'),
    ('Oso','Special Agent Oso',NULL,'The 21-year-old colorful special agent teddy bear who predominantly works on helping children perform tasks such as blowing bubbles, making a card or cleaning their rooms; he is the main character of the series.'),
    ('Oxsana','Borat',NULL,'Borat and Azamatt''s American black bear which they used for protection when traveling across the United States. She is named after Borat''s late wife whom was attacked and killed by a bear.'),
    ('P.T. Bridgeport','Pogo','Walt Kelly','A flamboyant impresario and traveling circus operator named after P.T. Barnum, with a theatrical speech pattern and carnival barker''s sales spiel satirizing the circus-like, media frenzy atmosphere of American political campaigns.[17]'),
    ('Paddington Bear','Paddington Bear','Michael Bond','A bear who emigrated from Peru to the station he was named after. First illustrated by Peggy Fortnum.'),
    ('Padistan Bear','Padistan Bear','John Warner','A young bear forced to leave home alone and make his way in the world. Illustrated by Angela Winstanley.'),
    ('Pancada','The Little Panda Fighter',NULL,'A panda bear working as the janitor at the Bear Bar Box who dreams of becoming a dancer, a boxing ring and bar that bears go to, to have a good time. Or they would, but few customers go to Bear Bar Box because the same bear Teddy Thunders has been champion for two years. The ring''s owner Mr. Polaris, a polar bear, plans to fight Teddy Thunders in the ring, but has to fight in disguise, but when Pancada does his laundry his black suit shrinks making Mr. Polaris look like a panda. Mr. Polaris wins the match, but everyone thinks that was Pancada, so Pancada now has to deal with the guilt of his unearned fame.'),
    ('Panda','Shirokuma Cafe',NULL,NULL),
    ('Panda','Panda','Marten Toonder','A little intelligent panda bear.[3]'),
    ('Panda','Tekken 3','Namco','Companion of Ling Xiaoyu.'),
    ('Panda Bear','We Bare Bears',NULL,'One of three brothers trying to fit in with human society.'),
    ('Panda King','Sly Cooper and the Thievius Raccoonus','Sucker Punch Productions','Pyrotechnics expert of the Fiendish Five and in the third game recruited to be part of the Cooper Gang.'),
    ('Panny','Panda! Go, Panda!',NULL,NULL),
    ('PapaPanda','Panda! Go, Panda!',NULL,NULL),
    ('Paw Paw Chuck','Paws & Tales',NULL,'Grizzly bear and folksy mentor of C.J. Brown and his friends.'),
    ('Peetie the Sexual Harassment Panda','South Park',NULL,'A man known normally as Tom Morris, he is a misfit educational mascot dressed as a panda who teaches children about sexual harassment. He eventually becomes "Peetie the Don''t Sue People Panda" to end the crisis of South Park citizens suing various people constantly.'),
    ('Penny Ling','Littlest Pet Shop',NULL,NULL),
    ('Pepper','Summer Camp Island',NULL,'A panda normally seen with his security blanket. He has a somewhat neurotic personality at times.'),
    ('Peter','Snowdrop''s Zoo','Arnold Warden','A sidekick of Chic the clown.[13]'),
    ('Peter the Panda','Phineas and Ferb',NULL,'A secret agent panda from Seattle.'),
    ('Ping','Jungle Jinks','Mabel Francis Taylor','A panda friend of the main cast.[14]'),
    ('Placid','Placid et Muzo [15]','José Cabrero Arnal',NULL),
    ('Polar','Crash Bandicoot 2: Cortex Strikes Back','Naughty Dog','Polar bear cub and pet of Crash Bandicoot.[34]'),
    ('Polar Bear','Shirokuma Cafe',NULL,'The proprietor of the café, which serves organic foods and drinks and is popular with both humans and animals. He has a habit of making bad puns with his customers and friends, just for the amusement of hearing their retorts.'),
    ('Poler Kamrous','Mega Man Zero 2','Capcom','Robotic polar bear encountered as a boss in Antarctica, where she guards a defense system computer.[35]'),
    ('Pooky','Garfield','Jim Davis','Garfield''s Teddy Bears'),
    ('Pop','Happy Tree Friends',NULL,'Cub''s father, who usually causes misfortune for his son casually or through negligence.'),
    ('Popol et Virginie','Popol Out West','Hergé','Two bears who visit the United States where they encounter Native American rabbits.[16]'),
    ('Professor Paljas','Alfred J. Kwak',NULL,NULL),
    ('Punch','Hustle Punch',NULL,'The main character: a street child bear.'),
    ('Queen Elinor','Brave',NULL,'Mérida''s mother who is transformed into a bear for two days by her daughter''s purchased spell with unforeseen consequences.'),
    ('Rasmus Klump','Rasmus Klump','Carla and Vilhelm Hansen','A little bear who owns a boat with which he travels the world.[18]'),
    ('Rebecca Cunningham','TaleSpin',NULL,NULL),
    ('Rilakkuma','Rilakkuma',NULL,'"Relax Bear" and his friend Korilakkuma, are a highly popular bear characters in Japan from the San-X Company.'),
    ('Ringbear','How I Met Your Mother',NULL,'The ring bearer at Barney and Robin''s wedding.'),
    ('Roro','Shirobako',NULL,NULL),
    ('Rupert Bear','Rupert Bear','Mary Tourtel','A little polar bear who wears a red shirt and yellow scarf.[19]'),
    ('Rupert Bear','Rupert Bear','Mary Tourtel','Also known as Rupert the Bear.'),
    ('Sana','Armello','League of Geeks','Chosen hero of the Bear Clan attuned with nature.[36]'),
    ('Sebastian Star Bear','Sebastian Star Bear: First Mission',NULL,'An extraterrestrial Star Bear from the Ursa Major constellation who flies to Earth in his CRYOG after hearing Griselda''s plea for help.'),
    ('Shao May','Fullmetal Alchemist: Brotherhood',NULL,NULL),
    ('Shardik','Shardik','Richard Adams',NULL),
    ('Smolder the Bear','The Lion King''s Timon and Pumbaa',NULL,'Smolder the Bear is a recurring character in the Timon and Pumbaa TV series.'),
    ('Sonny','Rimba Racer',NULL,NULL),
    ('Sonya the Bear','Madagascar 3: Europe''s Most Wanted',NULL,'King Julien''s love interest.'),
    ('Sooty','The Sooty Show',NULL,'A glove puppet bear, created by Harry Corbett in 1948, that appears on British television.'),
    ('State O'' Maine','The Hotel New Hampshire','John Irving','An oddly intelligent performing bear who works with Freud, a Viennese Jew.'),
    ('Storvacker','Dragon Age: Inquisition','Bioware','Stone-Bear Hold''s Hold-Beast in the Jaws of Hakkon DLC.'),
    ('SuperTed','SuperTed',NULL,'A teddy bear, found to be defective in the toy factory he was made in, was discarded. A Spotty man found him there and Mother Nature brought him to life with her "cosmic dust".'),
    ('Taotao','Taotao',NULL,NULL),
    ('Ted','Ted',NULL,'A Talking teddy bear.'),
    ('Ted E. Bear','The Bear Who Slept Through Christmas',NULL,'Theodore Edward (Ted E.) Bear goes exploring while the other bears are hibernating.'),
    ('Ted the Polar Bear','The Madagascar Penguins in a Christmas Caper',NULL,'Starts off with a lonely Christmas until Private decides to get him a present.'),
    ('Teddy','A.I. Artificial Intelligence',NULL,'The robotic toy bear belonging to David, a robot himself.'),
    ('Teddy Robinson','The Teddy Robinson Storybook','Joan G. Robinson','Cuddly but accident-prone, Teddy Robinson belongs to a little girl named Deborah.'),
    ('Teddy Ruxpin','The Adventures of Teddy Ruxpin',NULL,'Better known as "The World''s First Animated Talking Toy".'),
    ('Téodor Orezcu','Achewood','Chris Onstad',NULL),
    ('Teri','The Amazing World of Gumball',NULL,'A paper cutout bear and student at Elmore Junior High.'),
    ('The Buddy Bears','Garfield and Friends',NULL,'Singing annoying bears that ''always get along''.'),
    ('The Grizz','Sly Cooper: Thieves in Time','Sucker Punch Productions','Graffiti artist turned bad and now under the command of Cyrille Le Paradox.'),
    ('The Gummi Bears','Disney''s Adventures of the Gummi Bears',NULL,'Fictional group of anthropomorphic bears who have a long and rich history, and are relatively unknown to the humans of the world who believe that they are legends and fairy tales.'),
    ('The Hair Bear Bunch!','Help!... It''s the Hair Bear Bunch!',NULL,'Three fun-loving bears – the fast-talking Hair Bear (voiced by Daws Butler), bafflegab-talking Bubi Bear (voiced by Paul Winchell), and laid-back Square Bear (voiced by William Callaway) – who are always trying to find a way to escape from the Wonderland Zoo on some sort of get-rich-quick scheme, or a wild night of fun.'),
    ('The Hillbilly Bears','The Hillbilly Bears',NULL,'The Hillbilly Bears, a Hanna-Barbera Productions animated television series, featuring Paw Rugg, Maw Rugg, Floral Rugg, and Shag Rugg.'),
    ('The Squishy Bearz','Eek! The Cat',NULL,'Parodic versions of the Care Bears, consisting of Kozy, Puffy, Wuz Wuz and Pierre.'),
    ('The Three Bears','Looney Tunes',NULL,'The Three Bears are a family that consists of Papa Bear (sometimes called Henry), Mama Bear, and Junior Bear (sometimes spelled Junyer or Joonyer).'),
    ('The Three Bears','The Three Bears','Leo Baxendale','A bear family modelled after the famous fairytale and consisting of Pa Bear, Ma Bear and young son Ted.[20]'),
    ('The Three Bears','Goldilocks and the Three Bears','Robert Southey','Story of a little girl who enters into a house owned by three bears and causes a ruckus.'),
    ('Tim the Bear','The Cleveland Show',NULL,'One of Cleveland and Donna''s neighbors in Stoolbend. He is thirty-five years old and lives with his wife, Arianna, and his son, Raymond. He has deep religious convictions (often attending Stoolbend Community Church and having his honeymoon in Israel). He works as a telemarketer at Waterman Cable.'),
    ('Tobby','Tim und Tobby','Becker-Kasch','A bear who is best friends with a little fox.[21]'),
    ('Tottles','Tottles the Bear','Humphry Bowen',NULL),
    ('Ulfsaar the Ursa Warrior','Defense of the Ancients','Kyle Sommer','Ulfsaar the Warrior is the fiercest member of an Ursine Tribe.[37]'),
    ('Umka','Umka',NULL,'A polar bear cub, who befriended a boy from Nenets tribe. However, people left this territory, and Umka decides to find the boy.'),
    ('Uranus','Duckman',NULL,'One of Duckman''s two Care Bear-esque teddy-bear office assistants. Uranus is blue. Uranus and his co worker Fluffy try to get Duckman to act kindly and more politically correct.'),
    ('Ursinho Bilu','Monica''s Gang','Mauricio de Sousa','A metafictional cartoon character.'),
    ('Victor','Victor & Maria',NULL,NULL),
    ('Vincent','Over The Hedge',NULL,'An American black bear who is the antagonist from the film.'),
    ('Vladimir Goudenov Grizzlikof','Darkwing Duck',NULL,'A grizzly bear and S.H.U.S.H.''s top agent'),
    ('Volibear','League of Legends','Riot Games','A fierce and respected warrior of the Ursine.[38]'),
    ('Waldo','"The Waldo Moment" episode of Black Mirror',NULL,'A computer generated, human animated foul-mouthed television celebrity.'),
    ('Wally Bear','Wally Bear and the NO! Gang','American Game Cartridges','Title character and anti-drug advocate.[39]'),
    ('Winkie','Winkie','Clifford Chase',NULL),
    ('Winnie the Pooh','Disney''s Winnie the Pooh',NULL,'Based on the original stories of the same name by A.A. Milne and E.H. Shepard.'),
    ('Winnie-the-Pooh','Winnie-the-Pooh','A. A. Milne','Described as a bear of very little brain, yet has good ideas when helping with his friends.'),
    ('Yogi Bear','The Yogi Bear Show',NULL,'Yogi Bear resides in Jellystone Park and would often try to steal picnic baskets while evading Ranger Smith.'),
    ('Yumil','Lollipop Chainsaw','Grasshopper Manufacture','The undead companion of Viking metal zombie Vikke.'),
    ('Zozi','Bartok the Magnificent',NULL,NULL);
